// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFgnxYumjA9WCHEutAa8dhlp-KGEx-Xo',
    appId: '1:750349058073:web:08afd1504ec5bca97daa88',
    messagingSenderId: '750349058073',
    projectId: 'dream-example',
    authDomain: 'dream-example.firebaseapp.com',
    storageBucket: 'dream-example.appspot.com',
    measurementId: 'G-NQW8TE1CNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GiEcGKw9ZwvzZHTF2gx1tWyJOhC7AM0',
    appId: '1:750349058073:android:4f30f0b17d6dff987daa88',
    messagingSenderId: '750349058073',
    projectId: 'dream-example',
    storageBucket: 'dream-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAavlnW8JCYj53EGbIcbd0la5vO94RGO7U',
    appId: '1:750349058073:ios:7189919eac763e987daa88',
    messagingSenderId: '750349058073',
    projectId: 'dream-example',
    storageBucket: 'dream-example.appspot.com',
    iosBundleId: 'com.dreamacademy.daExample',
  );
}
